CREATE DATABASE ACME;
CREATE DATABASE ACMER;

CREATE LOGIN schemaspy WITH PASSWORD = 'qwerty123!'

USE ACME;

CREATE SCHEMA ACME_A;
CREATE SCHEMA ACME_B;

CREATE USER schemaspy FOR LOGIN schemaspy WITH DEFAULT_SCHEMA = ACME_A;
ALTER ROLE db_owner ADD MEMBER schemaspy;

CREATE TABLE acme_dbo_group
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL
);

CREATE TABLE acme_dbo_user
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL,
  GroupId INT NOT NULL,
  CONSTRAINT fk_group FOREIGN KEY (GroupId) REFERENCES acme_dbo_group (Id)
);

CREATE TABLE ACME_A.acme_a_group
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL
);

CREATE TABLE ACME_A.acme_a_user
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL,
  GroupId INT NOT NULL,
  CONSTRAINT fk_group FOREIGN KEY (GroupId) REFERENCES ACME_A.acme_a_group (Id)
);

CREATE TABLE ACME_B.acme_b_group
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL
);

CREATE TABLE ACME_B.acme_b_user
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL,
  GroupId INT NOT NULL,
  CONSTRAINT fk_group FOREIGN KEY (GroupId) REFERENCES ACME_B.acme_b_group (Id)
);

USE ACMER;

CREATE SCHEMA ACMER_A;
CREATE SCHEMA ACMER_B;

CREATE USER schemaspy FOR LOGIN schemaspy WITH DEFAULT_SCHEMA = ACMER_A;
ALTER ROLE db_owner ADD MEMBER schemaspy;

CREATE TABLE abc_dbo_group
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL
);

CREATE TABLE abc_dbo_user
(
 Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
 Name NVARCHAR(40) NOT NULL,
 Description NVARCHAR(100) NOT NULL,
 GroupId INT NOT NULL,
 CONSTRAINT fk_group FOREIGN KEY (GroupId) REFERENCES abc_dbo_group (Id)
);

CREATE TABLE ACMER_A.abc_a_group
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL
);

CREATE TABLE ACMER_A.abc_a_user
(
 Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
 Name NVARCHAR(40) NOT NULL,
 Description NVARCHAR(100) NOT NULL,
 GroupId INT NOT NULL,
 CONSTRAINT fk_group FOREIGN KEY (GroupId) REFERENCES ACMER_A.abc_a_group (Id)
);

CREATE TABLE ACMER_B.abc_a_group
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL
);

CREATE TABLE ACMER_B.abc_a_user
(
  Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(40) NOT NULL,
  Description NVARCHAR(100) NOT NULL,
  GroupId INT NOT NULL,
  CONSTRAINT fk_group FOREIGN KEY (GroupId) REFERENCES ACMER_B.abc_a_group (Id)
);
