CREATE SCHEMA "h2view" AUTHORIZATION SA;
SET SCHEMA "h2view";
CREATE TABLE "TABLE1"(
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255)
);
CREATE TABLE "TABLE2"(
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255)
);
CREATE VIEW THE_VIEW (NAMES) AS SELECT NAME FROM TABLE1 UNION SELECT NAME FROM TABLE2;