/*
 * Copyright (C) 2004 - 2011 John Currier
 * Copyright (C) 2016 Rafal Kasa
 *
 * This file is a part of the SchemaSpy project (http://schemaspy.org).
 *
 * SchemaSpy is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * SchemaSpy is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.schemaspy.output.dot.schemaspy;

import org.schemaspy.output.dot.DotConfig;
import org.schemaspy.output.dot.schemaspy.name.Name;

import java.io.PrintWriter;

/**
 * Format table data into .dot format to feed to Graphvis' dot program.
 *
 * @author John Currier
 * @author Rafal Kasa
 * @author Nils Petzaell
 */
public class DotFormat {

    private final DotConfig dotConfig;
    private Name diagram;
    private boolean showLabel;
    private PrintWriter dot;

    @Deprecated
    public DotFormat(DotConfig dotConfig) {
        this.dotConfig = dotConfig;
    }

    public DotFormat(
            final DotConfig dotConfig,
            final Name diagram,
            final boolean showLabel,
            final PrintWriter dot
    ) {
        this.dotConfig = dotConfig;
        this.diagram = diagram;
        this.showLabel = showLabel;
        this.dot = dot;
    }

    @Deprecated
    public void writeHeader(String diagramName, boolean showLabel, PrintWriter dot) {
        dot.println("digraph \"" + diagramName + "\" {");
        dot.println("  graph [");
        boolean rankdirbug = dotConfig.isRankDirBugEnabled();
        if (!rankdirbug)
            dot.println("    rankdir=\"RL\"");
        dot.println("    bgcolor=\"" + StyleSheet.getInstance().getBodyBackground() + "\"");
        if (showLabel) {
            if (rankdirbug)
                dot.println("    label=\"\\nLayout is significantly better without '-rankdirbug' option\"");
            else
                dot.println("    label=\"\\nGenerated by SchemaSpy\"");
            dot.println("    labeljust=\"l\"");
        }
        dot.println("    nodesep=\"0.18\"");
        dot.println("    ranksep=\"0.46\"");
        dot.println("    fontname=\"" + dotConfig.getFont() + "\"");
        dot.println("    fontsize=\"" + dotConfig.getFontSize() + "\"");
        dot.println("    ration=\"compress\"");
        dot.println("  ];");
        dot.println("  node [");
        dot.println("    fontname=\"" + dotConfig.getFont() + "\"");
        dot.println("    fontsize=\"" + dotConfig.getFontSize() + "\"");
        dot.println("    shape=\"plaintext\"");
        dot.println("  ];");
        dot.println("  edge [");
        dot.println("    arrowsize=\"0.8\"");
        dot.println("  ];");
    }

    public void writeHeader() {
        writeHeader(diagram.value(), showLabel, dot);
    }
}
