CREATE TABLESPACE orait DATAFILE '/u01/app/oracle/oradata/XE/orait.dbf' SIZE 50M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
CREATE TEMPORARY TABLESPACE oraittmp TEMPFILE '/u01/app/oracle/oradata/XE/oraittmp.dbf' SIZE 20M REUSE EXTENT MANAGEMENT LOCAL UNIFORM SIZE 16M;
CREATE USER orait IDENTIFIED BY orait123 DEFAULT TABLESPACE orait QUOTA 100M ON orait TEMPORARY TABLESPACE oraittmp;
GRANT CREATE SESSION TO orait;
GRANT CREATE TABLE TO orait;
CREATE TABLE orait.test (id NUMBER(3,0) PRIMARY KEY, name VARCHAR2(15));
COMMENT on COLUMN orait.test.name IS 'the name';