CREATE TABLESPACE db DATAFILE '/u01/app/oracle/oradata/XE/db.dbf' SIZE 50M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
CREATE TEMPORARY TABLESPACE dbtmp TEMPFILE '/u01/app/oracle/oradata/XE/dbtmp.dbf' SIZE 20M REUSE EXTENT MANAGEMENT LOCAL UNIFORM SIZE 16M;
CREATE USER dbuser IDENTIFIED BY dbuser123 DEFAULT TABLESPACE db QUOTA 100M ON db TEMPORARY TABLESPACE dbtmp;
GRANT CREATE SESSION TO dbuser;
GRANT CREATE TABLE TO dbuser;
CREATE TABLE dbuser.GIWSDURATIONHISTORY (GIWSDURATIONHISTORYID NUMBER(12,0) NOT NULL ENABLE,
	DURATIONHISTORYID NUMBER(12,0) NOT NULL ENABLE,
	WORKSTATIONID NUMBER(12,0),
	USERNAME VARCHAR2(30 CHAR) NOT NULL ENABLE,
	GOODSINPOSID NUMBER(12,0),
	QTY NUMBER(15,3) NOT NULL ENABLE,
	RESERVED VARCHAR2(255 CHAR),
	MODVERSION NUMBER(12,0) NOT NULL ENABLE,
	GENDAT DATE NOT NULL ENABLE,
	GENINFO VARCHAR2(1000 CHAR) NOT NULL ENABLE,
	MODDAT DATE NOT NULL ENABLE,
	MODINFO VARCHAR2(1000 CHAR) NOT NULL ENABLE,
	CONSTRAINT PK_GIWSDURATIONHISTORYL PRIMARY KEY (GIWSDURATIONHISTORYID)
  USING INDEX (CREATE UNIQUE INDEX dbuser.PK_GIWSDURATIONHISTORY ON dbuser.GIWSDURATIONHISTORY (GIWSDURATIONHISTORYID))  ENABLE);